noxlogic_rate_limit:
  enabled: true
  storage_engine: redis
  redis_client: default
  redis_service: \Predis\Client
  php_redis_service: \Redis
  memcache_client: null
  memcache_service: null
  doctrine_provider: null
  doctrine_service: null
  #  rate_response_code: 429
  #rate_response_exception: App\API\Exception\RatelimitException
  #rate_response_message: 'you exceeded the rate limit'
  display_headers: true
  headers:
    limit: X-RateLimit-Limit
    remaining: X-RateLimit-Remaining
    reset: X-RateLimit-Reset

